<a href="https://colab.research.google.com/github/PoussyAyman/IR/blob/main/Assignment2_pytherrier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Assignment 2)

Use the LinkeddIN dataset provided and do the following:


1.   Preprocessing and Indexing using **DFIndexer**
2. How many times did the Job "AI" appearead and provide the Job IDs?
You have to return a LIST CONTAINING ALL THE JOBIDS THAT CONTAINS THE JOB

An example of the desired output:
![image.png]()

In [ ]:
#install the Pyterrier framework
!pip install python-terrier
# install the nltk modules
!pip install nltk

Requirement already satisfied: python-terrier in /usr/local/lib/python3.10/dist-packages (0.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.25.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.5.3)
Requirement already satisfied: wget in /usr/local/lib/python3.10/dist-packages (from python-terrier) (3.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from python-terrier) (4.66.2)
Requirement already satisfied: pyjnius>=1.4.2 in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.6.1)
Requirement already satisfied: matchpy in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.5.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.2.2)
Requirement already satisfied: deprecated in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.2.14)
Requirement already satisfied: chest in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.11.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from python-terrier) (2.31.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.3.2)
Requirement already satisfied: nptyping==1.4.4 in /usr/local/lib/python3.10/dist-packages (from python-terrier) (1.4.4)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.10/dist-packages (from python-terrier) (10.1.0)
Requirement already satisfied: ir-datasets>=0.3.2 in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.5.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from python-terrier) (3.1.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.14.1)
Requirement already satisfied: ir-measures>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.3.3)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.3.8)
Requirement already satisfied: pytrec-eval-terrier>=0.5.3 in /usr/local/lib/python3.10/dist-packages (from python-terrier) (0.5.6)
Requirement already satisfied: typish>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from nptyping==1.4.4->python-terrier) (1.9.3)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (4.12.3)
Requirement already satisfied: inscriptis>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (2.5.0)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (4.9.4)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (6.0.1)
Requirement already satisfied: trec-car-tools>=2.5.4 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (2.6)
Requirement already satisfied: lz4>=3.1.10 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (4.3.3)
Requirement already satisfied: warc3-wet>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (0.2.3)
Requirement already satisfied: warc3-wet-clueweb09>=0.2.5 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (0.2.5)
Requirement already satisfied: zlib-state>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (0.1.6)
Requirement already satisfied: ijson>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (3.2.3)
Requirement already satisfied: pyautocorpus>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (0.1.12)
Requirement already satisfied: unlzw3>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from ir-datasets>=0.3.2->python-terrier) (0.2.2)
Requirement already satisfied: cwl-eval>=1.0.10 in /usr/local/lib/python3.10/dist-packages (from ir-measures>=0.3.1->python-terrier) (1.0.12)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->python-terrier) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->python-terrier) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->python-terrier) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->python-terrier) (2024.2.2)
Requirement already satisfied: heapdict in /usr/local/lib/python3.10/dist-packages (from chest->python-terrier) (1.0.1)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated->python-terrier) (1.14.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->python-terrier) (2.1.5)
Requirement already satisfied: multiset<3.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from matchpy->python-terrier) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->python-terrier) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->python-terrier) (2023.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->python-terrier) (3.3.0)
Requirement already satisfied: patsy>=0.5.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels->python-terrier) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels->python-terrier) (23.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.4.1->ir-datasets>=0.3.2->python-terrier) (2.5)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.4->statsmodels->python-terrier) (1.16.0)
Requirement already satisfied: cbor>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from trec-car-tools>=2.5.4->ir-datasets>=0.3.2->python-terrier) (1.0.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.2)

In [ ]:
import pyterrier as pt
if not pt.started():
  pt.init()

In [ ]:
#Import the necessary modules:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import *
from nltk.stem.porter import *
import re # used to clean the data
#to display the full text on the notebook without truncation
pd.set_option('display.max_colwidth', 150)

In [ ]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
import pandas as pd

df = pd.read_csv('/content/linkdin_Job_data.csv')

In [ ]:
df

          job_ID                                                job
0     3471657636  Data Analyst, Trilogy (Remote) - $60,000/year USD
1     3471669068  Data Analyst, Trilogy (Remote) - $60,000/year USD
2     3474349934                                 Data Analyst - WFH
3     3472816027                                       Data Analyst
4     3473311511                                       Data Analyst
...          ...                                                ...
7922  3472039871                                 Back End Developer
7923  3473194471                         Software Engineer - Senior
7924  3461005032                                             Vue JS
7925  3474305684                                      iOS Developer
7926  3459352801                     Power train function developer

[7927 rows x 2 columns]

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def remove_stopwords(text):
    try:
        tokens = word_tokenize(text)
    except TypeError:
        return ''

    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word.lower() for word in tokens if word.lower() not in stop_words]
    print('Tokens are:', tokens, '\n')
    return ' '.join(filtered_tokens)

# Apply the remove_stopwords function to the 'job' column
df['processed_text'] = df['job'].apply(remove_stopwords)

Streaming output truncated to the last 5000 lines.
Tokens are: ['Web', 'Designer-', 'Shopify']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Machine', 'Learning', 'Consultant']

Tokens are: ['Senior', 'Manager', '-', 'Sales', '(', 'Healthcare', 'Logistics/Global', 'Freight', 'Forwarding', ')']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Business', 'Analyst', '(', 'presales', ')']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead.NET', 'Developer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Customer', 'Support', '-', 'Team', 'Lead']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Data', 'Modeler']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['JVP', '-Solution', 'Consulting']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Senior', 'Scrum', 'Master']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['RPA', 'Business', 'analyst', 'with', 'UI', 'Path', '-', 'Immediate', 'Joiner']

Tokens are: ['Business', 'Development', 'Executive', '(', 'Online', 'Bider', ')']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['System', 'Administrator']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Data', 'Migration', 'Consultant', '(', 'In', 'Salesforce', ')']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Business', 'Analyst/Project', 'Coordinator']

Tokens are: ['Power', 'BI', 'Analyst']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['JavaScript', 'Development', 'Team', 'Lead']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Data', 'Engineer']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Data', 'Scientist']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Sr', '.', 'Manager', '-', 'Sales']

Tokens are: ['Flutter', 'Developer']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['CBS', '(', 'Ingeniero', 'de', 'Mejora', 'Continua', ')', 'Specialist']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['AR/VR', 'Technical', 'Developer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['JDA', 'Allocation', 'Planning']

Tokens are: ['Senior', 'Consultant']

Tokens are: ['Ping', 'Directory']

Tokens are: ['Java', 'Team', 'Lead']

Tokens are: ['Java', 'Team', 'Lead']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer', '(', 'JavaScript', ')']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Teacher']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Team', 'Lead', 'Scrum', 'Master']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Senior', 'Build', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Research', 'Analyst']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Data', 'Scientist']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Business', 'Analyst']

Tokens are: ['Consultant']

Tokens are: ['Microsoft', 'Dynamics', 'Consultant']

Tokens are: ['Dental', 'Assistant']

Tokens are: ['Online', 'Tutor']

Tokens are: ['SAP', 'Convergent', 'Charging', 'Analyst']

Tokens are: ['Operations', 'Analyst', '(', 'Contractual', 'Role', ')']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Java', 'Full', 'Stack', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Unreal', 'Game', 'Developer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Team', 'Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Learning', 'And', 'Development', 'Specialist']

Tokens are: ['Lead', 'Software', 'Test', 'Automation', 'Engineer']

Tokens are: ['Java', 'Full', 'Stack', 'Engineer']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Lead', 'ReactJS', 'Developer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Adobe', 'AEM', 'Developer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Big', 'Data', 'Developer']

Tokens are: ['Business', 'Analyst', '-', 'Generic']

Tokens are: ['Senior', 'Data', 'Quality', 'Engineer']

Tokens are: ['Java', 'Spring', 'Developer', '(', 'WFH', ')']

Tokens are: ['Senior', 'Scrum', 'Master']

Tokens are: ['Senior', 'Scrum', 'Master']

Tokens are: ['Data', 'Analyst', '(', 'India', ')']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Data', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Big', 'Data', 'Developer']

Tokens are: ['Manager', '-', 'Finance', 'and', 'Accounts']

Tokens are: ['DATA', 'Manager']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Java', 'Team', 'Lead']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Human', 'Resources', 'Trainee']

Tokens are: ['Java', 'Software', 'Engineer', '(', 'WFH', ')']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Operations', 'Specialist']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Financial', 'Accountant']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Sitecore', 'Developer']

Tokens are: ['Lead.NET', 'Developer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Software', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Data', 'cloud', 'engineer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Software', 'Maintenance', 'Engineer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Scrum', 'Master']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Senior', 'US', 'IT', 'Recruiter']

Tokens are: ['Senior', 'Build', 'Engineer']

Tokens are: ['Quality', 'Engineering', 'Team', 'Lead']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Lead', 'Python', 'Automated', 'Testing', 'Developer']

Tokens are: ['Senior', 'Build', 'Engineer']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Lead', 'Staff', 'UX', 'Designer']

Tokens are: ['Business', 'Analyst']

Tokens are: ['JavaScript', 'Development', 'Team', 'Lead']

Tokens are: ['Floating', 'Staff', 'Payroll', 'Manager']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Network', 'Engineer', '-', 'Advanced']

Tokens are: ['Business', 'Development', 'Manager']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Business', 'Development', 'Representative']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Technical', 'Writer', '[', 'T500-6051', ']']

Tokens are: ['Public', 'Relations', 'Intern']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer', '(', 'JavaScript', ')']

Tokens are: ['Automated', 'Testing', 'Team', 'Lead']

Tokens are: ['Automated', 'Testing', 'Team', 'Lead']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer', '(', 'JavaScript', ')']

Tokens are: ['Computer', 'Aided', 'Design', 'Designer']

Tokens are: ['Lead', 'Automation', 'Tester', '(', 'JS', ')']

Tokens are: ['Senior', 'Business', 'Analyst']

Tokens are: ['Head', 'of', 'Marketing']

Tokens are: ['Lead', 'Software', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Business', 'Analyst', '(', 'Licensing', 'Lead', ')']

Tokens are: ['Integration', 'Developer', '(', 'WFH', ')']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Team', 'Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Java', 'Software', 'Engineer', '(', 'WFH', ')']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Unity', '3D', 'Developer-', 'WFH']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['IE', 'Test', 'Engineer']

Tokens are: ['Lead', 'Software', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Automated', 'Testing', 'Team', 'Lead']

Tokens are: ['Data', 'Analyst', '-', 'Motor', 'Underwriting']

Tokens are: ['Sales', 'Executive']

Tokens are: ['Data', 'Engineering', 'Expert']

Tokens are: ['Data', 'Engineer']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer', '(', 'JavaScript', ')']

Tokens are: ['Lead', 'Developer']

Tokens are: ['Process', 'Executive', '-', 'Credit', 'and', 'Collection']

Tokens are: ['CBS', 'Digitalization', 'Specialist']

Tokens are: ['Creative', 'supervisor']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Product', 'Strategy', 'Manager']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Software', 'Maintenance', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Financial', 'Analyst', '?', 'FP', '&', 'A']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Lead', 'JavaScript', 'Developer']

Tokens are: ['iOS', 'Mobile', 'Developer', '(', 'WFH', ')']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Digital', 'Marketing', 'Lead']

Tokens are: ['Senior', 'Data', 'Engineer']

Tokens are: ['Associate', 'Vice', 'President', '?', 'Commercial', 'Sales']

Tokens are: ['Lead', 'Consultant']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Blockchain', 'Hyperledger', 'Indy', 'Developer']

Tokens are: ['Information', 'Security', 'Analyst']

Tokens are: ['Technician', 'Team', 'Lead']

Tokens are: ['Digital', 'Marketing', 'Specialist']

Tokens are: ['Business', 'Development', '-', 'Staffing', 'and', 'recruiting', 'service']

Tokens are: ['JavaScript', 'Development', 'Team', 'Lead']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Senior', 'Build', 'Engineer']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Python', 'Automated', 'Testing', 'Developer']

Tokens are: ['Java', 'Technical', 'Lead']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Python', 'Automated', 'Testing', 'Developer']

Tokens are: ['Lead', 'QA', 'Automation', 'Engineer', '(', 'JS', ')']

Tokens are: ['Senior', 'Automation', 'Tester', 'In', 'JavaScript', 'For', 'Business', 'Company']

Tokens are: ['Senior', 'Technical', 'Writer']

Tokens are: ['Technical', 'Lead']

Tokens are: ['Sr.Business', 'System', 'Analyst']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Java', 'Team', 'Lead']

Tokens are: ['Inside', 'Sales', 'Specialist']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Lead', 'Software', 'Engineer']

Tokens are: ['Lead', '.NET', 'Developer', 'For', 'Business', 'Company']

Tokens are: ['Lead', '.NET', 'Developer', 'For', 'Business', 'Company']

Tokens are: ['Lead', 'Software', 'Engineer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['JavaScript', 'Development', 'Team', 'Lead']

Tokens are: ['Data', 'Entry', '/', 'Video', 'Finder']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Senior', 'Java', 'Software', 'Engineer']

Tokens are: ['Senior', 'Manager-FP', '&', 'A']

Tokens are: ['Java', 'Team', 'Lead']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Senior', 'Java', 'Software', 'Engineer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'Backend', 'Developer']

Tokens are: ['Lead', 'Java/Golang', 'Developer']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.Net', 'Developer']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['.NET', 'Team', 'Lead']

Tokens are: ['Data', 'Scientist']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Java/Golang', 'Developer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Software', 'Engineer']

Tokens are: ['Senior', 'Build', 'Engineer']

Tokens are: ['Lead', 'ReactJS', 'Developer']

Tokens are: ['Data', 'Scientist']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'Automation', 'Software', 'Quality', 'Engineer']

Tokens are: ['Lead', 'Back-end', 'Developer']

Tokens are: ['Senior', 'Full-Stack', 'Developer']

Tokens are: ['Senior', 'Full-Stack', 'Developer']

Tokens are: ['Lead', 'Java/Golang', 'Developer']

Tokens are: ['Senior', '.NET', 'Developer', 'For', 'Business', 'Company']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', '.NET', 'Developer']

Tokens are: ['Senior', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'Automated', 'Testing', 'Engineer']

Tokens are: ['Lead', 'Java', 'Engineer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automated', 'Testing', 'Engineer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Team', 'Lead', 'Java', 'Software', 'Engineer']

Tokens are: ['Lead', 'Automation', 'Tester']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Software', 'Test', 'Automation', 'Engineer']

Tokens are: ['Lead', 'Test', 'Automation', 'Engineer', '(', 'JavaScript', ')']

Tokens are: ['Senior', 'Front-End', 'Developer', 'For', 'Healthcare', 'Company']

Tokens are: ['Senior', '.NET', 'Developer', 'For', 'Business', 'Company']

Tokens are: ['.NET', 'Development', 'Team', 'Lead']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['.NET', 'Team', 'Lead']

Tokens are: ['Senior', 'ReactJS', 'Developer']

Tokens are: ['Senior', 'Automation', 'Tester']

Tokens are: ['Lead', 'Kofax', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'JS', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Account', 'Executive']

Tokens are: ['Lead', 'Java', 'Developer']

Tokens are: ['Lead', 'Java', 'Developer']

Tokens are: ['Senior', '.NET', 'Developer']

Tokens are: ['Senior', '.NET', 'Developer']

Tokens are: ['Python', 'Developer']

Tokens are: ['Senior', 'Developer']

Tokens are: ['Automated', 'Driving', 'Software', 'Quality', 'Assurance', 'Engineer']

Tokens are: ['Senior', '.NET', 'Developer', 'For', 'Healthcare', 'Company']

Tokens are: ['Senior', '.NET', 'Developer', 'For', 'Healthcare', 'Company']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Senior', 'Test', 'Automation', 'Engineer']

Tokens are: ['Senior', 'Java/Golang', 'Engineer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Lead', 'Back-end', 'Developer']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Java', 'Development', 'Team', 'Lead']

Tokens are: ['Lead', '.NET', 'Developer']

Tokens are: ['Web', 'CPS', 'Affiliate', 'Manager']

Tokens are: ['Deputy', 'General', 'Manager', '-', 'Customer', 'Success', 'and', 'Quality', '||', 'Permanent', 'hiring', 'for', 'a', 'leading', 'European', 'MNC']

Tokens are: ['Technical', 'Business', 'Analyst']

Tokens are: ['Data', 'Science', 'Manager']

Tokens are: ['Business', 'Development', 'Executive']

Tokens are: ['Quality', 'Assurance', 'Test', 'Lead', ',', 'Data', 'and', 'BI', 'projects']

Tokens are: ['Big', 'Data', 'Java', 'Chapter', 'Manager']

Tokens are: ['Sr', 'Corporate', 'Tax', 'Analyst', '(', 'Sales', '&', 'Use', 'Tax', ')']

Tokens are: ['Senior', 'Data', 'Scientist']

Tokens are: ['Mass', 'Tort', 'Data', 'Mining', 'Specialist']

Tokens are: ['Head', 'of', 'Ecommerce']

Tokens are: ['Web', 'Researcher', 'and', 'Analyst']

Tokens are: ['Malware', 'Analyst']

Tokens are: ['Sr', 'Salesforce', 'Business', 'Analyst']

Tokens are: ['Senior', 'Analyst']

Tokens are: ['Lead', 'Data', 'Scientist']

Tokens are: ['Information', 'Technology', 'Project', 'Coordinator']

Tokens are: ['Bid', 'Engineer']

Tokens are: ['Data', 'Ops', 'and', 'Insights', 'Manager']

Tokens are: ['Research', 'Associate-', 'Chemicals']

Tokens are: ['Cloud', 'Data', 'Architect', 'CoE']

Tokens are: ['Sr', 'Software', 'Engineer', '/', 'Data', 'Engineer', '(', 'Python', '+', 'ETL', ')']

Tokens are: ['Data', 'Science', 'Intern']

Tokens are: ['Data', 'Architect']

Tokens are: ['Leasing', 'Specialist']

Tokens are: ['Technical', 'Consultant-', 'Data', 'Integration']

Tokens are: ['Sr.', 'Security', 'Analyst']

Tokens are: ['Manager', ',', 'Data', 'Warehouse', 'Lead', '(', 'Commercial', 'IT', ')']

Tokens are: ['Java', 'Support', ':', '-', 'Client', 'Services', 'Analyst']

Tokens are: ['centre', 'Sales', 'associate']

Tokens are: ['Senior', 'Business', 'Analyst', '-', 'Salesforce']


In [ ]:
print('dataFrame after processing:\n')
df

dataFrame after processing:

,job_ID,job,processed_text
0,3471657636,"Data Analyst, Trilogy (Remote) - $60,000/year USD","data analyst , trilogy ( remote ) - $ 60,000/year usd"
1,3471669068,"Data Analyst, Trilogy (Remote) - $60,000/year USD","data analyst , trilogy ( remote ) - $ 60,000/year usd"
2,3474349934,Data Analyst - WFH,data analyst - wfh
3,3472816027,Data Analyst,data analyst
4,3473311511,Data Analyst,data analyst
...,...,...,...
7922,3472039871,Back End Developer,back end developer
7923,3473194471,Software Engineer - Senior,software engineer - senior
7924,3461005032,Vue JS,vue js
7925,3474305684,iOS Developer,ios developer
7926,3459352801,Power train function developer,power train function developer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
def steem_text(text):
  tokens = word_tokenize(text)
  stemmed_tokens = [stemmer.stem(word) for word in tokens]
  return ' '.join(stemmed_tokens)
  df['processed_text']=df['job'].apply(Steem_text)
df

,job_ID,job,processed_text
0,3471657636,"Data Analyst, Trilogy (Remote) - $60,000/year USD","data analyst , trilogy ( remote ) - $ 60,000/year usd"
1,3471669068,"Data Analyst, Trilogy (Remote) - $60,000/year USD","data analyst , trilogy ( remote ) - $ 60,000/year usd"
2,3474349934,Data Analyst - WFH,data analyst - wfh
3,3472816027,Data Analyst,data analyst
4,3473311511,Data Analyst,data analyst
...,...,...,...
7922,3472039871,Back End Developer,back end developer
7923,3473194471,Software Engineer - Senior,software engineer - senior
7924,3461005032,Vue JS,vue js
7925,3474305684,iOS Developer,ios developer
7926,3459352801,Power train function developer,power train function developer

In [ ]:
indexer = pt.DFIndexer("./myFirstIndex", overwrite=True)

# index the text, record the docnos as metadata
df["job_ID"] = df["job_ID"].astype(str)
index_ref = indexer.index(df["job"], docno=df["job_ID"])

13:42:55.375 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:42:55.428 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:56.920 [main] WARN org.terrier.structures.indexing.Indexer - Adding an empty document to the index (3466169448) - further warnings are suppressed
13:42:57.384 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:42:57.446 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:42:57.495 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:57.673 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:58.172 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:42:58.227 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:58.676 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:59.039 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:42:59.227 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:59.773 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:42:59.874 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:42:59.997 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:00.115 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:00.300 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:00.696 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:00.754 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:01.831 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:02.171 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:02.206 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:02.299 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:02.978 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:03.196 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:03.602 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:03.699 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:04.028 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:04.766 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:05.705 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:05.775 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:05.888 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:06.044 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document
13:43:06.090 [main] WARN org.terrier.structures.indexing.Indexer - skipping null document

Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'
Traceback (most recent call last):
  File "jnius/jnius_proxy.pxi", line 50, in jnius.PythonJavaClass.invoke
  File "jnius/jnius_proxy.pxi", line 76, in jnius.PythonJavaClass._invoke
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 778, in next
    lastdoc = self.convertFn(text, meta)
  File "/usr/local/lib/python3.10/dist-packages/pyterrier/index.py", line 687, in convertDoc
    return TaggedDocument(StringReader(text_row), hashmap, Tokeniser.getTokeniser())
  File "jnius/jnius_export_class.pxi", line 269, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 362, in jnius.JavaClass.call_constructor
  File "jnius/jnius_conversion.pxi", line 74, in jnius.populate_args
  File "jnius/jnius_utils.pxi", line 193, in jnius.check_assignable_from_str
TypeError: Invalid instance of 'java/lang/Float' passed for a 'java/lang/String'

13:43:07.217 [main] WARN org.terrier.structures.indexing.Indexer - Indexed 1 empty documents

In [ ]:
print(index_ref.toString())
index= pt.IndexFactory.of(index_ref)
print(index.getCollectionStatistics().toString())

./myFirstIndex/data.properties
Number of documents: 7894
Number of terms: 1552
Number of postings: 26332
Number of fields: 0
Number of tokens: 26553
Field names: []
Positions:   false

# From the Documentation

In [ ]:
listt = []
inv = index.getInvertedIndex()
meta = index.getMetaIndex()
lex = index.getLexicon()

le = lex.getLexiconEntry("ai")
wmodel = pt.autoclass("org.terrier.matching.models.PL2")()
wmodel.setCollectionStatistics(index.getCollectionStatistics())
wmodel.setEntryStatistics(le)
wmodel.setKeyFrequency(1)
wmodel.prepare()

for posting in inv.getPostings(le):
    docno = meta.getItem("docno", posting.getId())
    listt.append(docno)
print(listt)
# count = 0
# for i in range (len(listt)):
#   count +=1
# print(count)

['3467845449', '3472867935', '3472867935', '3465491143', '3466109330', '3404404287', '3463049864', '3469027470', '3469058629', '3476535998', '3474481881', '3473954908', '3469043009', '3469066440', '3476171085', '3469027470', '3469058629', '3474874901', '3476535998', '3474481881', '3469043009', '3473693758', '3462492847', '3466686457', '3466686533', '3467211659', '3472136504', '3473551455', '3467211627', '3469066440', '3462434504', '3464443804', '3466109330', '3467321571', '3467321571', '2374955526', '3469701642', '3471195239', '3474478316', '3476519606', '3476535998', '3473551455', '3473548941', '3469701642', '3466686457']

In [ ]:
print('Document ferquency',index.getLexicon()["ai"].getDocumentFrequency())

Document ferquency 45

In [ ]:
df =df[df['processed_text'].str.contains('ai',case = False)]
count = len(df)
print('term ferquency:',count)

term ferquency: 335